// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogINPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logINPage() {
    driver.get("https://careercenter.tops-int.com/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.id("mobile")).click();
    driver.findElement(By.id("mobile")).sendKeys("6353306381");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Jarvis Mark42");
    driver.findElement(By.cssSelector(".mt-3 > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mt-3 > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#course-dropdown > .pe-3")).click();
    driver.findElement(By.linkText("Assignment")).click();
    driver.findElement(By.id("profileDropdown")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.cssSelector(".fa")).click();
  }
}
